### ISSUE TITLE
No folders inside the bucket downloaded only files.

### ISSUE THREAD

**Issue by sbibek** [eschwartz/s3-sync#2]
Only files are being downloaded instead of entire things inside the bucket.

**Comment by eschwartz** [comment]
Not entirely sure what you mean. Can you please walk through:
- What you're doing (how to reproduce)
- What you're expecting
- What you're actually getting

Looking through the code, it could be there we're missing a `--recursive` flag [here](https://github.com/eschwartz/s3-sync/blob/master/lib/s3-client.js#L55), but it's hard to say, if I don't understand your issue.

**Comment by eschwartz** [comment]
not enough info here.. closing the issue
