### ISSUE TITLE
Cannot find module 'aeris-s3-sync' NPM

### ISSUE THREAD

**Issue by scramble45** [eschwartz/s3-sync#3]
pulled module down via npm

When requiring the module using:
````
var S3Client = require('aeris-s3-sync');
or
var S3Client = require('S3Client');
````

Cannot find module 'aeris-s3-sync'
Cannot find module 'S3Client'

Looks like your package.json is pointed to the wrong file it should be:
"main": "lib/s3-client.js",

**Comment by eschwartz** [comment]
Sorry about that -- I actually have a fix for the package.json on `master`, that I just never published.

You should be able to get it working now using v1.0.1

~Also `var S3Client = require('S3Client');` isn't going to work. This library requires an S3 client from the AWS node SDK (sorry if that's not well documented).~

~I believe it should be:..~

EDIT: sorry, I'm wrong. You _don't_ need to inject a client from the AWS SDK. This lib just wraps the AWS SDK, with it's own S3 client.

**Comment by scramble45** [comment]
Cool thanks for fixing it :+1:
